name: Backend CI (Java Spring Boot)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'clinica-backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  build:
    name: Compilar y Testear Backend
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: ☕ Configurar Java (JDK 21)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: ⚙️ Compilar el proyecto con Maven
      working-directory: ./clinica-backend
      run: mvn clean package -DskipTests

    - name: 📦 Subir el archivo .jar compilado como Evidencia
      uses: actions/upload-artifact@v4
      with:
        name: clinica-backend-build
        path: clinica-backend/target-cli/*.jar
        retention-days: 5
